// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	models "go_project/models"

	mock "github.com/stretchr/testify/mock"
)

// IPictureRepository is an autogenerated mock type for the IPictureRepository type
type IPictureRepository struct {
	mock.Mock
}

// FindPictureByDate provides a mock function with given fields: date
func (_m *IPictureRepository) FindPictureByDate(date string) (*models.Picture, error) {
	ret := _m.Called(date)

	var r0 *models.Picture
	if rf, ok := ret.Get(0).(func(string) *models.Picture); ok {
		r0 = rf(date)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Picture)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(date)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ReadPicturesWithWorkerPool provides a mock function with given fields: criteria, items, maxJobsPerWorker
func (_m *IPictureRepository) ReadPicturesWithWorkerPool(criteria string, items int, maxJobsPerWorker int) ([]models.Picture, error) {
	ret := _m.Called(criteria, items, maxJobsPerWorker)

	var r0 []models.Picture
	if rf, ok := ret.Get(0).(func(string, int, int) []models.Picture); ok {
		r0 = rf(criteria, items, maxJobsPerWorker)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Picture)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, int, int) error); ok {
		r1 = rf(criteria, items, maxJobsPerWorker)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SavePicture provides a mock function with given fields: picture
func (_m *IPictureRepository) SavePicture(picture *models.Picture) error {
	ret := _m.Called(picture)

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.Picture) error); ok {
		r0 = rf(picture)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
